---
- name: Install and Configure WordPress on Amazon Linux EC2
  hosts: wordpress
  become: true
  vars:
    db_name: "wordpress"
    db_host: "terraform-20241231203904201000000003.cdmig84qafp1.ap-southeast-1.rds.amazonaws.com:3306"
    db_user: "admin"
    db_password: "Wordpress"
    wp_admin_user: "admin"
    wp_admin_password: "Password"
    wp_admin_email: "mehta.deeksha2@gmail.com"
    website_dir: "/var/www/html"
    apache_package: "httpd"
    php_package: "php"
    mysql_client_package: "mysql"
    php_mysql_package: "php-mysqlnd"
  
  tasks:
    # Install Apache Web Server
    - name: Install Apache web server
      yum:
        name: "{{ apache_package }}"
        state: present

    # Install PHP and necessary PHP packages
    - name: Install PHP
      yum:
        name: "{{ php_package }}"
        state: present

    - name: Install PHP MySQL extension
      yum:
        name: "{{ php_mysql_package }}"
        state: present

    - name: Install Python libraries for MySQL
      package:
        name:
          - python3-pip
        state: present

    - name: Install PyMySQL
      pip:
        name: PyMySQL
        executable: pip3

    # Start Apache service and enable it on boot
    - name: Start Apache service
      service:
        name: "{{ apache_package }}"
        state: started
        enabled: yes

    # Download WordPress files
    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/latest.tar.gz"

    - name: Extract WordPress tarball
      unarchive:
        src: "/tmp/latest.tar.gz"
        dest: "{{ website_dir }}"
        remote_src: yes

    # Set the appropriate permissions on the WordPress directory
    - name: Set proper permissions for WordPress directory
      file:
        path: "{{ website_dir }}"
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    # Copy wp-config.php template to WordPress directory
    - name: Copy wp-config.php from template
      template:
        src: wp-config.php.j2
        dest: "{{ website_dir }}/wordpress/wp-config.php"
        owner: apache
        group: apache
        mode: '0644'

    # Restart Apache to apply changes
    - name: Restart Apache service
      service:
        name: "{{ apache_package }}"
        state: restarted

    # Test if WordPress is accessible (optional)
    - name: Check if WordPress is up and running
      uri:
        url: "http://{{ ansible_host }}/wordpress/"
        method: GET
        return_content: yes
      register: result

    - name: Show result of the test
      debug:
        var: result.content
