---
- name: Install WordPress on Ubuntu
  hosts: wordpress
  become: yes


  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install required packages for WordPress
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - wget
          - unzip
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set correct permissions for WordPress directory
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        state: directory
        recurse: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
